# Generated by Django 5.2.3 on 2025-06-29 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'PayrollPeriods',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['start_date'], name='idx_payroll_period_start_date'), models.Index(fields=['end_date'], name='idx_payroll_period_end_date')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['email'], name='idx_user_email'), models.Index(fields=['role'], name='idx_user_role')],
            },
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user')),
            ],
            options={
                'verbose_name_plural': 'SalaryHistories',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user_id'], name='idx_salary_history_user_id')],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user')),
            ],
            options={
                'verbose_name_plural': 'Salaries',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user_id'], name='idx_salary_user_id')],
            },
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_date', models.DateField()),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.payrollperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user')),
            ],
            options={
                'verbose_name_plural': 'Reimbursements',
                'ordering': ['claim_date'],
                'indexes': [models.Index(fields=['user_id'], name='idx_reimbursement_user_id'), models.Index(fields=['claim_date'], name='idx_reimbursement_claim_date'), models.Index(fields=['payroll_period_id'], name='idx_reimbursement_pp_id')],
            },
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_date', models.DateField()),
                ('hours', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.payrollperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user')),
            ],
            options={
                'verbose_name_plural': 'Overtimes',
                'ordering': ['clock_date'],
                'indexes': [models.Index(fields=['user_id'], name='idx_overtime_user_id'), models.Index(fields=['payroll_period_id'], name='idx_overtime_pp_id'), models.Index(fields=['clock_date'], name='idx_overtime_clock_date')],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_date', models.DateField()),
                ('clock_in', models.TimeField()),
                ('clock_out', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.payrollperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user')),
            ],
            options={
                'verbose_name_plural': 'Attendances',
                'ordering': ['clock_date'],
                'indexes': [models.Index(fields=['user_id'], name='idx_attendance_user_id'), models.Index(fields=['payroll_period_id'], name='idx_attendance_pp_id'), models.Index(fields=['clock_date'], name='idx_attendance_clock_date'), models.Index(fields=['clock_in'], name='idx_attendance_payroll_ci'), models.Index(fields=['clock_out'], name='idx_attendance_payroll_co')],
            },
        ),
    ]
