# Generated by Django 5.2.3 on 2025-06-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='EMPLOYEE', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user', 'clock_date')},
        ),
    ]
