# Generated by Django 5.2.3 on 2025-07-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_attendance_clock_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
