# Generated by Django 5.2.3 on 2025-07-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_attendance_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
