# Generated by Django 5.2.3 on 2025-07-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_reimbursement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiod',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
