# Generated by Django 5.2.3 on 2025-07-01 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_payrollperiod_processed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.FloatField()),
                ('salary_per_hour', models.FloatField()),
                ('attended_days', models.IntegerField()),
                ('attended_percentage', models.FloatField()),
                ('overtime_hours', models.FloatField()),
                ('overtime_pay', models.FloatField()),
                ('reimbursement_amount', models.FloatField()),
                ('take_home_salary', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.payrollperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payrolls',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='idx_payroll_created_at')],
            },
        ),
    ]
